# Generated by Django 2.1 on 2019-01-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spiderbot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
